name: wsms
description: A new Flutter project.

# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.0.21+25

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  page_transition: ^2.0.2
  http: ^0.13.3
  flutter_spinkit: ^5.0.0
  shared_preferences: ^2.0.6
  cached_network_image: ^3.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  fluttertoast: ^8.0.7
  syncfusion_flutter_calendar: ^19.2.48
  firebase_messaging: ^10.0.4
  flutter_local_notifications: ^6.1.0
  firebase_core: ^1.4.0
  provider: ^5.0.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  flutter_html: ^2.1.1
  jiffy: ^4.1.0
  lottie: ^1.1.0
  syncfusion_flutter_gauges: ^19.2.59
  flutter_zoom_sdk: ^0.0.6
  intl: ^0.17.0
  permission_handler: ^8.1.6
  jitsi_meet: ^4.0.0
  new_version: ^0.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.2.1

flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true



flutter_native_splash:
  color: "#FCFCFC"
  image: assets/logo.png
  android: true
  ios: true

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
